sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t truongdev2021/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true truongdev2021/react-test npm test

after_success:
  - docker build -t truongdev2021/multi-client ./client
  - docker build -t truongdev2021/multi-nginx ./nginx
  - docker build -t truongdev2021/multi-server ./server
  - docker build -t truongdev2021/multi-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push truongdev2021/multi-client
  - docker push truongdev2021/multi-nginx
  - docker push truongdev2021/multi-server
  - docker push truongdev2021/multi-worker

deploy:
  provider: elasticbeanstalk
  region: "us-west-2"
  app: "multi-docker"
  env: "Multi-docker-env"
  bucket_name: "elasticbeanstalk-us-west-2-605057357249"
  bucket_path: "multi-docker"
  on:
    branch: master
  access_key_id: "$AWS_ACCESS_KEY"
  secret_access_key: "$AWS_SECRET_KEY"
